const TokenType = {
    LEFT_PAREN: 'LEFT_PAREN', // '('
    RIGHT_PAREN: 'RIGHT_PAREN', // ')'
    LEFT_BRACE: 'LEFT_BRACE', // '{'
    RIGHT_BRACE: 'RIGHT_BRACE', // '}'
    LEFT_SQUARE: 'LEFT_SQUARE', // '['
    RIGHT_SQUARE: 'RIGHT_SQUARE', // ']'
    COMMA: 'COMMA', // ','
    PERIOD: 'PERIOD', // '.'
    MINUS: 'MINUS', // '-',
    MINUS_MINUS: 'MINUS_MINUS', // '--'
    MINUS_EQUAL: 'MINUS_EQUAL', // '-='
    PLUS: 'PLUS', // '+'
    PLUS_PLUS: 'PLUS_PLUS', // '++'
    PLUS_EQUAL: 'PLUS_EQUAL', // '+='
    COLON: 'COLON', // ':'
    SEMICOLON: 'SEMICOLON', // ';'
    PIPE: 'PIPE', // '|'
    PIPE_PIPE: 'PIPE_PIPE', // '||'
    PIPE_EQUAL: 'PIPE_EQUAL', // '|='
    SLASH: 'SLASH', // '/'
    SLASH_EQUAL: 'SLASH_EQUAL', // '/='
    STAR: 'STAR', // '*'
    STAR_EQUAL: 'STAR_EQUAL', // '*='
    PERCENT: 'PERCENT', // '%'
    PERCENT_EQUAL: 'PERCENT_EQUAL', // '%='
    EXCLAIM: 'EXCLAIM', // '!'
    EXCLAIM_EQUAL: 'EXCLAIM_EQUAL', // '!='
    EQUAL: 'EQUAL', // '='
    EQUAL_EQUAL: 'EQUAL_EQUAL', // '=='
    GREATER: 'GREATER', // '>'
    GREATER_EQUAL: 'GREATER_EQUAL', // '>='
    LESS: 'LESS', // '<'
    LESS_EQUAL: 'LESS_EQUAL', // '<='
    AMPERSAND: 'AMPERSAND', // '&'
    AMPERSAND_EQUAL: 'AMPERSAND_EQUAL', // '&='
    AMPERSAND_AMPERSAND: 'AMPERSAND_AMPERSAND', // '&&'
    QUESTION: 'QUESTION', // '?'
    IDENTIFIER: 'IDENTIFIER',
    STRING: 'STRING',
    NUMBER: 'NUMBER',
    AND: 'AND', // 'and'
    OR: 'OR', // 'or'
    CLASS: 'CLASS', // 'class'
    PUBLIC: 'PUBLIC', // 'public'
    PRIVATE: 'PRIVATE', // 'private'
    PROTECTED: 'PROTECTED', // 'protected'
    STRUCTURE: 'STRUCTURE', // 'structure'
    FUNCTION: 'FUNCTION', // 'function'
    FOR: 'FOR', // 'for'
    IF: 'IF', // 'if'
    ELSE: 'ELSE', // 'else'
    NIL: 'NIL', // 'nil'
    DO: 'DO', // 'do'
    RETURN: 'RETURN', // 'return'
    SUPER: 'SUPER', // 'super'
    SELF: 'SELF', // 'self'
    TRUE: 'TRUE', // 'true'
    FALSE: 'FALSE', // 'false'
    VAR: 'VAR', // 'var'
    CONST: 'CONST', // 'const'
    WHILE: 'WHILE', // 'while'
    BREAK: 'BREAK', // 'break'
    CONTINUE: 'CONTINUE', // 'continue'
    EOF: 'EOF',
};

Object.freeze(TokenType);

export default TokenType;
